//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMiner_Controll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMiner_Controll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;pools&quot; : [
        ///{
        ///&quot;url&quot; : &quot;#URL1#&quot;,
        ///&quot;user&quot; : &quot;#USER1#&quot;,
        ///&quot;pass&quot; : &quot;#PW1#&quot;
        ///},
        ///{
        ///&quot;url&quot; : &quot;#URL2#&quot;,
        ///&quot;user&quot; : &quot;#USER2#&quot;,
        ///&quot;pass&quot; : &quot;#PW2#&quot;
        ///},
        ///{
        ///&quot;url&quot; : &quot;#URL3#&quot;,
        ///&quot;user&quot; : &quot;#USER3#&quot;,
        ///&quot;pass&quot; : &quot;#PW3#&quot;
        ///}
        ///]
        ///,
        ///&quot;api-listen&quot; : true,
        ///&quot;api-network&quot; : true,
        ///&quot;api-groups&quot; : &quot;A:stats:pools:devs:summary:version&quot;,
        ///&quot;api-allow&quot; : &quot;W:0/0&quot;,
        ///&quot;bitmain-fan-ctrl&quot; : true,
        ///&quot;bitmain-fan-pwm&quot; : &quot;100&quot;,
        ///&quot;bitmain-use-vil&quot; : true,
        ///&quot;bitmain-freq&quot; : &quot;0&quot;
        ///}.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
    }
}
